services:
  postgres:
    image: postgres:16

    container_name: payment-postgres

    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"